In [117]:
import numpy as np
import pandas as pd

In [118]:
data = np.load('./data/METRLA/data.npz')["data"].astype(np.float32)
index = np.load('./data/METRLA/index.npz')

In [119]:
data[0]

array([[64.375  ,  0.     ,  3.     ],
       [67.625  ,  0.     ,  3.     ],
       [67.125  ,  0.     ,  3.     ],
       [61.5    ,  0.     ,  3.     ],
       [66.875  ,  0.     ,  3.     ],
       [68.75   ,  0.     ,  3.     ],
       [65.125  ,  0.     ,  3.     ],
       [67.125  ,  0.     ,  3.     ],
       [59.625  ,  0.     ,  3.     ],
       [62.75   ,  0.     ,  3.     ],
       [55.5    ,  0.     ,  3.     ],
       [66.5    ,  0.     ,  3.     ],
       [64.25   ,  0.     ,  3.     ],
       [68.5    ,  0.     ,  3.     ],
       [60.375  ,  0.     ,  3.     ],
       [67.5    ,  0.     ,  3.     ],
       [37.75   ,  0.     ,  3.     ],
       [63.125  ,  0.     ,  3.     ],
       [59.75   ,  0.     ,  3.     ],
       [62.125  ,  0.     ,  3.     ],
       [67.25   ,  0.     ,  3.     ],
       [41.25   ,  0.     ,  3.     ],
       [54.625  ,  0.     ,  3.     ],
       [58.125  ,  0.     ,  3.     ],
       [65.125  ,  0.     ,  3.     ],
       [64.25   ,  0.    

In [28]:
features = [0]    
features.append(1)
features.append(2)
# if dom:
#     features.append(3)
data = data[..., features]
print(data.shape)

(34272, 207, 3)


In [57]:
data[0]

array([[64.375  ,  0.     ,  3.     ],
       [67.625  ,  0.     ,  3.     ],
       [67.125  ,  0.     ,  3.     ],
       [61.5    ,  0.     ,  3.     ],
       [66.875  ,  0.     ,  3.     ],
       [68.75   ,  0.     ,  3.     ],
       [65.125  ,  0.     ,  3.     ],
       [67.125  ,  0.     ,  3.     ],
       [59.625  ,  0.     ,  3.     ],
       [62.75   ,  0.     ,  3.     ],
       [55.5    ,  0.     ,  3.     ],
       [66.5    ,  0.     ,  3.     ],
       [64.25   ,  0.     ,  3.     ],
       [68.5    ,  0.     ,  3.     ],
       [60.375  ,  0.     ,  3.     ],
       [67.5    ,  0.     ,  3.     ],
       [37.75   ,  0.     ,  3.     ],
       [63.125  ,  0.     ,  3.     ],
       [59.75   ,  0.     ,  3.     ],
       [62.125  ,  0.     ,  3.     ],
       [67.25   ,  0.     ,  3.     ],
       [41.25   ,  0.     ,  3.     ],
       [54.625  ,  0.     ,  3.     ],
       [58.125  ,  0.     ,  3.     ],
       [65.125  ,  0.     ,  3.     ],
       [64.25   ,  0.    

In [31]:
test = data[...,[0,1]]
print(test.shape)

(34272, 207, 2)


In [32]:
train_index = index["train"]  # (num_samples, 3)
val_index = index["val"]
test_index = index["test"]

In [38]:
from lib.utils import vrange

x_train_index = vrange(train_index[:, 0], train_index[:, 1])
y_train_index = vrange(train_index[:, 1], train_index[:, 2])

In [46]:
x_train_index.shape, y_train_index[..., :1]

((23974, 12),
 array([[   12],
        [   13],
        [   14],
        ...,
        [23983],
        [23984],
        [23985]], dtype=int64))

In [41]:
data[x_train_index].shape

(23974, 12, 207, 3)

In [55]:
y_train = data[y_train_index][..., 0:1]
y_train[0][0]

array([[61.125   ],
       [67.      ],
       [58.5     ],
       [62.25    ],
       [66.375   ],
       [67.5     ],
       [63.125   ],
       [68.375   ],
       [56.      ],
       [65.71429 ],
       [60.5     ],
       [70.      ],
       [65.75    ],
       [63.375   ],
       [58.25    ],
       [66.875   ],
       [36.125   ],
       [66.125   ],
       [54.375   ],
       [63.      ],
       [68.125   ],
       [56.75    ],
       [55.5     ],
       [58.75    ],
       [66.875   ],
       [68.      ],
       [58.25    ],
       [65.375   ],
       [56.75    ],
       [49.25    ],
       [11.      ],
       [65.625   ],
       [69.125   ],
       [66.      ],
       [66.      ],
       [57.625   ],
       [53.75    ],
       [59.5     ],
       [56.      ],
       [63.375   ],
       [64.5     ],
       [63.375   ],
       [64.375   ],
       [60.5     ],
       [65.875   ],
       [61.625   ],
       [62.75    ],
       [56.75    ],
       [57.857143],
       [60.25    ],


In [35]:
train_index[:, 0], train_index[:, 1]

(array([    0,     1,     2, ..., 23971, 23972, 23973], dtype=int64),
 array([   12,    13,    14, ..., 23983, 23984, 23985], dtype=int64))

In [36]:
train_index

array([[    0,    12,    24],
       [    1,    13,    25],
       [    2,    14,    26],
       ...,
       [23971, 23983, 23995],
       [23972, 23984, 23996],
       [23973, 23985, 23997]], dtype=int64)

In [59]:
import pandas as pd
data = pd.read_csv("./data/SWAT/test.csv")
data    

Unnamed: 0    FIT101    LIT101  MV101  P101  P102    AIT201    AIT202  \
0               0  0.943239  0.458333    1.0   1.0   0.0  0.627270  0.256121   
1               1  0.939214  0.457240    1.0   1.0   0.0  0.627270  0.251304   
2               2  0.893011  0.458378    1.0   1.0   0.0  0.627270  0.251304   
3               3  0.956481  0.459226    1.0   1.0   0.0  0.627270  0.253311   
4               4  0.917571  0.460565    1.0   1.0   0.0  0.627270  0.249297   
...           ...       ...       ...    ...   ...   ...       ...       ...   
44986       44986  0.916287  0.452218    1.0   1.0   0.0 -2.703411  0.560016   
44987       44987  0.915062  0.451214    1.0   1.0   0.0 -2.703411  0.562826   
44988       44988  0.950589  0.453713    1.0   1.0   0.0 -2.703411  0.565234   
44989       44989  0.897503  0.453780    1.0   1.0   0.0 -2.703411  0.567241   
44990       44990  0.955431  0.450723    1.0   1.0   0.0 -2.703411  0.566840   

         AIT203    FIT201  ...  P501  P502    PIT501    PIT502    PIT503  \
0      0.104221  0.981817  ...   1.0   0.0  0.946157  0.449782  0.943791   
1      0.104221  0.981457  ...   1.0   0.0  0.947378  0.449782  0.945860   
2      0.104221  0.980684  ...   1.0   0.0  0.947378  0.449782  0.945576   
3      0.103356  0.980684  ...   1.0   0.0  0.945718  0.449782  0.944075   
4      0.103356  0.980684  ...   1.0   0.0  0.945092  0.449782  0.942980   
...         ...       ...  ...   ...   ...       ...       ...       ...   
44986  0.003702  0.988616  ...   1.0   0.0  0.947378  0.266376  0.940790   
44987  0.004711  0.987019  ...   1.0   0.0  0.947065  0.253275  0.940060   
44988  0.003750  0.987483  ...   1.0   0.0  0.947190  0.231441  0.940466   
44989  0.003750  0.988281  ...   1.0   0.0  0.948036  0.266376  0.941277   
44990  0.003750  0.989132  ...   1.0   0.0  0.947503  0.257642  0.940507   

         FIT601  P601  P602  P603  attack  
0      0.000073   0.0   0.0   0.0     0.0  
1      0.000073   0.0   0.0   0.0     0.0  
2      0.000073   0.0   0.0   0.0     0.0  
3      0.000073   0.0   0.0   0.0     0.0  
4      0.000073   0.0   0.0   0.0     0.0  
...         ...   ...   ...   ...     ...  
44986  0.000000   0.0   0.0   0.0     0.0  
44987  0.000000   0.0   0.0   0.0     0.0  
44988  0.000000   0.0   0.0   0.0     0.0  
44989  0.000000   0.0   0.0   0.0     0.0  
44990  0.000000   0.0   0.0   0.0     0.0  

[44991 rows x 53 columns]

In [61]:
data = data.iloc[:,1:]

In [62]:
data.shape

(44991, 52)

In [64]:
arr = data.to_numpy()
arr = arr.reshape(44991,52,1)

In [65]:
arr.shape

(44991, 52, 1)

In [66]:
data = arr
np.savez('./data/SWAT/data.npz', data = arr)

In [70]:
data.shape

(44991, 52, 1)

In [68]:
index.files

['train', 'val', 'test']

In [71]:
index['train'].shape

(23974, 3)

In [79]:
list1 = []
list2 = []
list3 = []
for i in range(0,34976):
    list1.append(i)
    list2.append(i+12)
    list3.append(i+24)
train = [list1, list2, list3]
train = np.array(train)

In [82]:
train.shape
train

array([[    0,     1,     2, ..., 34973, 34974, 34975],
       [   12,    13,    14, ..., 34985, 34986, 34987],
       [   24,    25,    26, ..., 34997, 34998, 34999]])

In [84]:
train = np.transpose(train)
train

array([[    0,    12,    24],
       [    1,    13,    25],
       [    2,    14,    26],
       ...,
       [34973, 34985, 34997],
       [34974, 34986, 34998],
       [34975, 34987, 34999]])

In [86]:
list1 = []
list2 = []
list3 = []
for i in range(35000,39976):
    list1.append(i)
    list2.append(i+12)
    list3.append(i+24)
val = [list1, list2, list3]
val = np.array(val)
val = val.transpose()
val

array([[35000, 35012, 35024],
       [35001, 35013, 35025],
       [35002, 35014, 35026],
       ...,
       [39973, 39985, 39997],
       [39974, 39986, 39998],
       [39975, 39987, 39999]])

In [88]:
list1 = []
list2 = []
list3 = []
for i in range(40000,44968):
    list1.append(i)
    list2.append(i+12)
    list3.append(i+24)
test = [list1, list2, list3]
test = np.array(test)
test = test.transpose()
test

array([[40000, 40012, 40024],
       [40001, 40013, 40025],
       [40002, 40014, 40026],
       ...,
       [44965, 44977, 44989],
       [44966, 44978, 44990],
       [44967, 44979, 44991]])

In [89]:
np.savez('./data/SWAT/index.npz', train = train, val = val, test = test)

In [90]:
import h5py
f = h5py.File('./data/metr-la.h5')

In [99]:
for name in f:
    print(name)
    for dataset_name in f[name]:
        dataset = f[name][dataset_name]
        print(dataset_name,dataset.shape)
print(f['df']['block0_values'][0])

df
axis0 (207,)
axis1 (34272,)
block0_items (207,)
block0_values (34272, 207)
[64.375      67.625      67.125      61.5        66.875      68.75
 65.125      67.125      59.625      62.75       55.5        66.5
 64.25       68.5        60.375      67.5        37.75       63.125
 59.75       62.125      67.25       41.25       54.625      58.125
 65.125      64.25       61.25       62.75       66.875      47.375
 57.         67.75       65.125      66.875      64.         62.
 64.375      60.75       60.75       62.375      64.5        66.
 62.         64.875      55.875      67.75       63.         60.125
 60.25       62.25       42.25       48.25       65.125      63.5
 55.75       60.5        51.57142857 60.25       63.875      59.875
 64.625      64.         52.5        66.25       68.25       68.875
 66.375      64.5        67.875      67.25       63.125      66.25
 64.625      59.125      68.25       52.25       58.125      61.25
 66.125      69.375      69.75       63.5        64